CREATE TABLE  `MYSQL5_833260_logtest`.`LOG` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `DATE` DATETIME NOT NULL,
  `Thread` VARCHAR(32) NOT NULL,
  `Level` VARCHAR(10) NOT NULL,
  `Logger` VARCHAR(512) NOT NULL,
  `Message` VARCHAR(1000) NOT NULL,
  `Exception` VARCHAR(4000) DEFAULT NULL,
  
  PRIMARY KEY  (`ID`),
  INDEX `ix_log_level` (`Level`)
  ) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;