//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kululu.Web.Views.Playlist {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Playlist {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Playlist() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kululu.Web.Views.Playlist.Playlist", typeof(Playlist).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add song.
        /// </summary>
        public static string AddSong {
            get {
                return ResourceManager.GetString("AddSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to playlist.
        /// </summary>
        public static string backToPlaylist {
            get {
                return ResourceManager.GetString("backToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t add.
        /// </summary>
        public static string CancelAddSong {
            get {
                return ResourceManager.GetString("CancelAddSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to view in Facebook.
        /// </summary>
        public static string clickToViewPostInFB {
            get {
                return ResourceManager.GetString("clickToViewPostInFB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string deleteSong {
            get {
                return ResourceManager.GetString("deleteSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likes.
        /// </summary>
        public static string DialogComments_likes {
            get {
                return ResourceManager.GetString("DialogComments_likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you think?.
        /// </summary>
        public static string DialogComments_YourOpinion {
            get {
                return ResourceManager.GetString("DialogComments_YourOpinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string DialogDefaultCancel {
            get {
                return ResourceManager.GetString("DialogDefaultCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another time.
        /// </summary>
        public static string DialogFeedback_AnotherTime {
            get {
                return ResourceManager.GetString("DialogFeedback_AnotherTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I love kululu..
        /// </summary>
        public static string DialogFeedback_Content {
            get {
                return ResourceManager.GetString("DialogFeedback_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string DialogFeedback_Send {
            get {
                return ResourceManager.GetString("DialogFeedback_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s time to complain. What bothers you?.
        /// </summary>
        public static string DialogFeedback_Subtitle {
            get {
                return ResourceManager.GetString("DialogFeedback_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kululu - What do you think?.
        /// </summary>
        public static string DialogFeedback_Title {
            get {
                return ResourceManager.GetString("DialogFeedback_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We thank you .
        /// </summary>
        public static string DialogFeedbackThanks_Content {
            get {
                return ResourceManager.GetString("DialogFeedbackThanks_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you!.
        /// </summary>
        public static string DialogFeedbackThanks_Title {
            get {
                return ResourceManager.GetString("DialogFeedbackThanks_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete song.
        /// </summary>
        public static string DialogueTemplateDeleteSong_DeleteSong {
            get {
                return ResourceManager.GetString("DialogueTemplateDeleteSong_DeleteSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will also delete the post from facebook.
        /// </summary>
        public static string DialogueTemplateDeleteSong_Subtitle {
            get {
                return ResourceManager.GetString("DialogueTemplateDeleteSong_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete this song?.
        /// </summary>
        public static string DialogueTemplateDeleteSong_Title {
            get {
                return ResourceManager.GetString("DialogueTemplateDeleteSong_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of artist.
        /// </summary>
        public static string DialogueTemplateEditSong_ArtistName {
            get {
                return ResourceManager.GetString("DialogueTemplateEditSong_ArtistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of song.
        /// </summary>
        public static string DialogueTemplateEditSong_SongName {
            get {
                return ResourceManager.GetString("DialogueTemplateEditSong_SongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch image.
        /// </summary>
        public static string DialogueTemplateEditSong_SwitchPicture {
            get {
                return ResourceManager.GetString("DialogueTemplateEditSong_SwitchPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit song.
        /// </summary>
        public static string DialogueTemplateEditSong_Title {
            get {
                return ResourceManager.GetString("DialogueTemplateEditSong_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to edit.
        /// </summary>
        public static string DialogueTemplatePost_ClickToEdit {
            get {
                return ResourceManager.GetString("DialogueTemplatePost_ClickToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kululu! I just added a new song to this playlist:.
        /// </summary>
        public static string DialogueTemplatePost_Content {
            get {
                return ResourceManager.GetString("DialogueTemplatePost_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kululu! I really love this song!.
        /// </summary>
        public static string DialogueTemplatePost_Description {
            get {
                return ResourceManager.GetString("DialogueTemplatePost_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message will be posted on the groups wall, not yours. Now, let&apos;s edit it..
        /// </summary>
        public static string DialogueTemplatePost_SubTitle {
            get {
                return ResourceManager.GetString("DialogueTemplatePost_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new song.
        /// </summary>
        public static string DialogueTemplatePost_Title {
            get {
                return ResourceManager.GetString("DialogueTemplatePost_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone has already added this song. Perhaps it&apos;s up there and you haven&apos;t noticed?.
        /// </summary>
        public static string DialogueTemplatePostError_duplicateEntry {
            get {
                return ResourceManager.GetString("DialogueTemplatePostError_duplicateEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good work! but it seems you have passed the allowed limit..
        /// </summary>
        public static string DialogueTemplateSongLimit_Content {
            get {
                return ResourceManager.GetString("DialogueTemplateSongLimit_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey, leave some for other as well!.
        /// </summary>
        public static string DialogueTemplateSongLimit_Title {
            get {
                return ResourceManager.GetString("DialogueTemplateSongLimit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn&apos;t you like it?.
        /// </summary>
        public static string didYouNotLike {
            get {
                return ResourceManager.GetString("didYouNotLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t like.
        /// </summary>
        public static string disliked {
            get {
                return ResourceManager.GetString("disliked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t like?.
        /// </summary>
        public static string doYouNotLlike {
            get {
                return ResourceManager.GetString("doYouNotLlike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit song title.
        /// </summary>
        public static string editTitle {
            get {
                return ResourceManager.GetString("editTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest raters.
        /// </summary>
        public static string highVoters {
            get {
                return ResourceManager.GetString("highVoters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Love it.
        /// </summary>
        public static string iLiked {
            get {
                return ResourceManager.GetString("iLiked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It takes just a few seconds to add this app to your page..
        /// </summary>
        public static string InstallMe {
            get {
                return ResourceManager.GetString("InstallMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to my page.
        /// </summary>
        public static string InstallMeButton {
            get {
                return ResourceManager.GetString("InstallMeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboard.
        /// </summary>
        public static string leaderboard {
            get {
                return ResourceManager.GetString("leaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top songs.
        /// </summary>
        public static string leadingSongs {
            get {
                return ResourceManager.GetString("leadingSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop us a line.
        /// </summary>
        public static string leaveFeedback {
            get {
                return ResourceManager.GetString("leaveFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liked.
        /// </summary>
        public static string liked {
            get {
                return ResourceManager.GetString("liked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likes.
        /// </summary>
        public static string likes {
            get {
                return ResourceManager.GetString("likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music we like.
        /// </summary>
        public static string musicWeLike {
            get {
                return ResourceManager.GetString("musicWeLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My socring.
        /// </summary>
        public static string myScore {
            get {
                return ResourceManager.GetString("myScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New songs.
        /// </summary>
        public static string newSongsTab {
            get {
                return ResourceManager.GetString("newSongsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next song.
        /// </summary>
        public static string nextSong {
            get {
                return ResourceManager.GetString("nextSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string playlists {
            get {
                return ResourceManager.GetString("playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seach for song....
        /// </summary>
        public static string searchDefaultValueLookupSongs {
            get {
                return ResourceManager.GetString("searchDefaultValueLookupSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search or add a song.
        /// </summary>
        public static string searchDefaultValueTitle {
            get {
                return ResourceManager.GetString("searchDefaultValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I feel like listening to....
        /// </summary>
        public static string searchDefaultValueWantToHear {
            get {
                return ResourceManager.GetString("searchDefaultValueWantToHear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string share {
            get {
                return ResourceManager.GetString("share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more.
        /// </summary>
        public static string showMore {
            get {
                return ResourceManager.GetString("showMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show who liked and didn&apos;t like song.
        /// </summary>
        public static string showVotes {
            get {
                return ResourceManager.GetString("showVotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs.
        /// </summary>
        public static string songs {
            get {
                return ResourceManager.GetString("songs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I hate fun!.
        /// </summary>
        public static string templateConnect_Cancel {
            get {
                return ResourceManager.GetString("templateConnect_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to use the application , you must first connect with it.
        /// </summary>
        public static string templateConnect_Connect {
            get {
                return ResourceManager.GetString("templateConnect_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I ♥ Kululu ! (connect).
        /// </summary>
        public static string templateConnect_Login {
            get {
                return ResourceManager.GetString("templateConnect_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining kululu.
        /// </summary>
        public static string templateConnect_Title {
            get {
                return ResourceManager.GetString("templateConnect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation may take a long time (a few minutes)..
        /// </summary>
        public static string TemplateHarvestPreDialogue_Content {
            get {
                return ResourceManager.GetString("TemplateHarvestPreDialogue_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a period.
        /// </summary>
        public static string TemplateHarvestPreDialogue_Period {
            get {
                return ResourceManager.GetString("TemplateHarvestPreDialogue_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import songs.
        /// </summary>
        public static string TemplateHarvestPreDialogue_Title {
            get {
                return ResourceManager.GetString("TemplateHarvestPreDialogue_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize songs.
        /// </summary>
        public static string TemplateSynchronizePreDialogue_Title {
            get {
                return ResourceManager.GetString("TemplateSynchronizePreDialogue_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can go without it.
        /// </summary>
        public static string templateVotesDialogue_HateTheSong {
            get {
                return ResourceManager.GetString("templateVotesDialogue_HateTheSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Love this song.
        /// </summary>
        public static string templateVotesDialogue_LoveTheSong {
            get {
                return ResourceManager.GetString("templateVotesDialogue_LoveTheSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to votes.
        /// </summary>
        public static string votes {
            get {
                return ResourceManager.GetString("votes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall.
        /// </summary>
        public static string wall {
            get {
                return ResourceManager.GetString("wall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your rating.
        /// </summary>
        public static string yourScore {
            get {
                return ResourceManager.GetString("yourScore", resourceCulture);
            }
        }
    }
}
