// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Kululu.Web.Controllers {
    public partial class AccountController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AccountController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Index() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ShowDefaultScreen() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ShowDefaultScreen);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult Login() {
            return new T4MVC_JsonResult(Area, Name, ActionNames.Login);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult RecentActivity() {
            return new T4MVC_JsonResult(Area, Name, ActionNames.RecentActivity);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ChangeCulture() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ChangeCulture);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AccountController Actions { get { return MVC.Account; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Account";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Welcome = "Welcome";
            public readonly string Connect = "Connect";
            public readonly string Index = "Index";
            public readonly string Start = "Start";
            public readonly string ShowDefaultScreen = "ShowDefaultScreen";
            public readonly string Login = "Login";
            public readonly string RecentActivity = "RecentActivity";
            public readonly string CreateTestUser = "CreateTestUser";
            public readonly string ChangeCulture = "ChangeCulture";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string JoinUs = "~/Views/Account/JoinUs.cshtml";
            public readonly string TestUser = "~/Views/Account/TestUser.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_AccountController: Kululu.Web.Controllers.AccountController {
        public T4MVC_AccountController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Welcome() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Welcome);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Connect() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Connect);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Index(string name) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            callInfo.RouteValueDictionary.Add("name", name);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Start() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Start);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ShowDefaultScreen(long playlistId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ShowDefaultScreen);
            callInfo.RouteValueDictionary.Add("playlistId", playlistId);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult Login(string accessToken, long? playlistId) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.Login);
            callInfo.RouteValueDictionary.Add("accessToken", accessToken);
            callInfo.RouteValueDictionary.Add("playlistId", playlistId);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult RecentActivity(int offset, int amount) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.RecentActivity);
            callInfo.RouteValueDictionary.Add("offset", offset);
            callInfo.RouteValueDictionary.Add("amount", amount);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CreateTestUser() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CreateTestUser);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ChangeCulture(string lang, string returnUrl) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ChangeCulture);
            callInfo.RouteValueDictionary.Add("lang", lang);
            callInfo.RouteValueDictionary.Add("returnUrl", returnUrl);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
