// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Kululu.Web.Controllers {
    public partial class FbStreamHarvestController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected FbStreamHarvestController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public FbStreamHarvestController Actions { get { return MVC.FbStreamHarvest; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "FbStreamHarvest";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Init = "Init";
            public readonly string Synchronize = "Synchronize";
            public readonly string Import = "Import";
            public readonly string GetImportStatus = "GetImportStatus";
            public readonly string GetImportLikesComplete = "GetImportLikesComplete";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_FbStreamHarvestController: Kululu.Web.Controllers.FbStreamHarvestController {
        public T4MVC_FbStreamHarvestController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Init() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Init);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult Synchronize() {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.Synchronize);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult Synchronize(long localBusinessId, short type) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.Synchronize);
            callInfo.RouteValueDictionary.Add("localBusinessId", localBusinessId);
            callInfo.RouteValueDictionary.Add("type", type);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult Import() {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.Import);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult Import(long localBusinessId, short type) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.Import);
            callInfo.RouteValueDictionary.Add("localBusinessId", localBusinessId);
            callInfo.RouteValueDictionary.Add("type", type);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult GetImportStatus() {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.GetImportStatus);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult GetImportLikesComplete() {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.GetImportLikesComplete);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
