// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC {
    public class SharedController {

        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string _Footer = "~/Views/Shared/_Footer.cshtml";
            public readonly string _FooterSlim = "~/Views/Shared/_FooterSlim.cshtml";
            public readonly string _Globals = "~/Views/Shared/_Globals.cshtml";
            public readonly string _LayoutMain = "~/Views/Shared/_LayoutMain.cshtml";
            public readonly string _LayoutZero = "~/Views/Shared/_LayoutZero.cshtml";
            public readonly string BrowserNotSupported = "~/Views/Shared/BrowserNotSupported.cshtml";
            public readonly string ComeBackLater = "~/Views/Shared/ComeBackLater.cshtml";
            public readonly string Error = "~/Views/Shared/Error.cshtml";
            public readonly string Shared_he = "~/Views/Shared/Shared.he.resx";
            public readonly string Shared = "~/Views/Shared/Shared.resx";
            public readonly string Welcome = "~/Views/Shared/Welcome.cshtml";
            public readonly string Welcome_he = "~/Views/Shared/Welcome.he.resx";
            public readonly string Welcome_resx = "~/Views/Shared/Welcome.resx";
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
