//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kululu.Web.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kululu.Web.Views.Shared.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a day ago.
        /// </summary>
        public static string aDayAgo {
            get {
                return ResourceManager.GetString("aDayAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As playlist admin, you can add as many songs as you want..
        /// </summary>
        public static string adminNoLimit {
            get {
                return ResourceManager.GetString("adminNoLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ago.
        /// </summary>
        public static string ago {
            get {
                return ResourceManager.GetString("ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a minute ago.
        /// </summary>
        public static string aMinuteAgo {
            get {
                return ResourceManager.GetString("aMinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an hour ago.
        /// </summary>
        public static string anHoursAgo {
            get {
                return ResourceManager.GetString("anHoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a second ago.
        /// </summary>
        public static string aSecondAgo {
            get {
                return ResourceManager.GetString("aSecondAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a year ago.
        /// </summary>
        public static string aYearAgo {
            get {
                return ResourceManager.GetString("aYearAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kululu! So many songs I like!.
        /// </summary>
        public static string createSongDefaultDescription {
            get {
                return ResourceManager.GetString("createSongDefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kululu! I just add a new song to this playlist :.
        /// </summary>
        public static string createSongDefaultMessage {
            get {
                return ResourceManager.GetString("createSongDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} new songs..
        /// </summary>
        public static string didntVoteFor {
            get {
                return ResourceManager.GetString("didntVoteFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops. An error has occured. Cannot play song..
        /// </summary>
        public static string errorPlayingSong {
            get {
                return ResourceManager.GetString("errorPlayingSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liked.
        /// </summary>
        public static string femaleLiked {
            get {
                return ResourceManager.GetString("femaleLiked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn&apos;t Like.
        /// </summary>
        public static string femaleNotLiked {
            get {
                return ResourceManager.GetString("femaleNotLiked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Thanks for joining Kululu&lt;/h2&gt;&lt;p&gt;Buckle up and hold on! We start&lt;/p&gt;.
        /// </summary>
        public static string guideBuckleUp {
            get {
                return ResourceManager.GetString("guideBuckleUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t like fun (cancel).
        /// </summary>
        public static string guideButtonCancel {
            get {
                return ResourceManager.GetString("guideButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s start!.
        /// </summary>
        public static string guideButtonGo {
            get {
                return ResourceManager.GetString("guideButtonGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;First step - let&apos;s connect.&lt;br/&gt;That&apos;s how you select songs, rate and influence.&lt;/p&gt;.
        /// </summary>
        public static string guideFirstStage {
            get {
                return ResourceManager.GetString("guideFirstStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s start!.
        /// </summary>
        public static string guideLetsStart {
            get {
                return ResourceManager.GetString("guideLetsStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kululu!.
        /// </summary>
        public static string guideTitle {
            get {
                return ResourceManager.GetString("guideTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s start.
        /// </summary>
        public static string guideTutorialLetsStart {
            get {
                return ResourceManager.GetString("guideTutorialLetsStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it. What&apos;s next?.
        /// </summary>
        public static string guideTutorialNext {
            get {
                return ResourceManager.GetString("guideTutorialNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok. What&apos;s next?.
        /// </summary>
        public static string guideTutorialNext2 {
            get {
                return ResourceManager.GetString("guideTutorialNext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;How do you search or add a song?&lt;/h2&gt;&lt;p&gt;Just start typing as in Google. While you type Kululu looks up songs and shows you the results below.&lt;br/&gt;Now, just click the &amp;quot;Add/Like&amp;quot; button&lt;/p&gt;.
        /// </summary>
        public static string guideTutorialStep1 {
            get {
                return ResourceManager.GetString("guideTutorialStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Your points&lt;/h2&gt;&lt;p&gt;In Kululu you earn points. You get it for every action you take, like voting, adding songs and other things that you will have to discover yourself.&lt;br/&gt;You can show off with those points, or ask from the page owner to get you sime prize.&lt;/p&gt;.
        /// </summary>
        public static string guideTutorialStep2 {
            get {
                return ResourceManager.GetString("guideTutorialStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;New songs&lt;/h2&gt;&lt;p&gt;Here you can see how many songs you have not voted for yet.&lt;/p&gt;.
        /// </summary>
        public static string guideTutorialStep3 {
            get {
                return ResourceManager.GetString("guideTutorialStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am fine.
        /// </summary>
        public static string guideTutorialStop {
            get {
                return ResourceManager.GetString("guideTutorialStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&apos;quote&apos;&gt;So many songs, so little time! You just have to select with me.&lt;/p&gt;&lt;p&gt;Kululu is a social and fun way of selecting songs.&lt;/p&gt;&lt;p class=&apos;last&apos;&gt;All you have to do is to add songs that you love to the playlist and start voting.&lt;/p&gt;.
        /// </summary>
        public static string guideWelcome {
            get {
                return ResourceManager.GetString("guideWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liked.
        /// </summary>
        public static string maleLiked {
            get {
                return ResourceManager.GetString("maleLiked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to didn&apos;t like.
        /// </summary>
        public static string maleNotLiked {
            get {
                return ResourceManager.GetString("maleNotLiked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have one new song..
        /// </summary>
        public static string newSongs {
            get {
                return ResourceManager.GetString("newSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new songs..
        /// </summary>
        public static string noNewSongs {
            get {
                return ResourceManager.GetString("noNewSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to votes.
        /// </summary>
        public static string ratings {
            get {
                return ResourceManager.GetString("ratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot remove yourself as admin.
        /// </summary>
        public static string settingIndex_cannotRemoveYourself {
            get {
                return ResourceManager.GetString("settingIndex_cannotRemoveYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error with adding the users.
        /// </summary>
        public static string settingIndex_errorWhenAddingUser {
            get {
                return ResourceManager.GetString("settingIndex_errorWhenAddingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing.
        /// </summary>
        public static string settingIndex_harvestInit {
            get {
                return ResourceManager.GetString("settingIndex_harvestInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured! Your settings weren&apos;t saved..
        /// </summary>
        public static string settingIndex_settingsNotSaved {
            get {
                return ResourceManager.GetString("settingIndex_settingsNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you, all settings have been saved..
        /// </summary>
        public static string settingIndex_settingsSaved {
            get {
                return ResourceManager.GetString("settingIndex_settingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *This user is not an admin of the page.
        /// </summary>
        public static string settingIndex_userNotAdminContent {
            get {
                return ResourceManager.GetString("settingIndex_userNotAdminContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user cannot perform actions that demand him to be the page owner..
        /// </summary>
        public static string settingIndex_userNotAdminTitle {
            get {
                return ResourceManager.GetString("settingIndex_userNotAdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting ended. Cannot add new songs.
        /// </summary>
        public static string votingEnded {
            get {
                return ResourceManager.GetString("votingEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well done! You&apos;ve added all your allowed songs for today..
        /// </summary>
        public static string votingLimit {
            get {
                return ResourceManager.GetString("votingLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You still have {0} songs to add.
        /// </summary>
        public static string votingRemaining {
            get {
                return ResourceManager.GetString("votingRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting will end in.
        /// </summary>
        public static string votingWillEndIn {
            get {
                return ResourceManager.GetString("votingWillEndIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        public static string years {
            get {
                return ResourceManager.GetString("years", resourceCulture);
            }
        }
    }
}
