//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kululu.Web.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Welcome {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Welcome() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kululu.Web.Views.Shared.Welcome", typeof(Welcome).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s Rock!.
        /// </summary>
        public static string CallToAction {
            get {
                return ResourceManager.GetString("CallToAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a few seconds away from rocking your page..
        /// </summary>
        public static string CallToActionMotivation {
            get {
                return ResourceManager.GetString("CallToActionMotivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play all your Wall Videos..
        /// </summary>
        public static string Feature1 {
            get {
                return ResourceManager.GetString("Feature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Social Playlists..
        /// </summary>
        public static string Feature2 {
            get {
                return ResourceManager.GetString("Feature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reach Your Fans..
        /// </summary>
        public static string Feature3 {
            get {
                return ResourceManager.GetString("Feature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Contests..
        /// </summary>
        public static string Feature4 {
            get {
                return ResourceManager.GetString("Feature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward Your Audience..
        /// </summary>
        public static string Feature5 {
            get {
                return ResourceManager.GetString("Feature5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock your page with Kululu!.
        /// </summary>
        public static string Heading {
            get {
                return ResourceManager.GetString("Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are creating an application for your page. It should take a few seconds..
        /// </summary>
        public static string LoadingMessage1 {
            get {
                return ResourceManager.GetString("LoadingMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your patience..
        /// </summary>
        public static string LoadingMessage2 {
            get {
                return ResourceManager.GetString("LoadingMessage2", resourceCulture);
            }
        }
    }
}
