//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kululu.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Settings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Settings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kululu.Web.App_GlobalResources.Settings", typeof(Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string _new {
            get {
                return ResourceManager.GetString("_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string advance {
            get {
                return ResourceManager.GetString("advance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t set your import playing.
        /// </summary>
        public static string chooseImportPlaylistError {
            get {
                return ResourceManager.GetString("chooseImportPlaylistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist to import wall data into.
        /// </summary>
        public static string choseImportPlaylist {
            get {
                return ResourceManager.GetString("choseImportPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs a day.
        /// </summary>
        public static string dailySongLimit {
            get {
                return ResourceManager.GetString("dailySongLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require &quot;Like&quot; for using the application.
        /// </summary>
        public static string demandLike {
            get {
                return ResourceManager.GetString("demandLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string disable {
            get {
                return ResourceManager.GetString("disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit playlist.
        /// </summary>
        public static string EditPlaylist {
            get {
                return ResourceManager.GetString("EditPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string enable {
            get {
                return ResourceManager.GetString("enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string endDate {
            get {
                return ResourceManager.GetString("endDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting end date.
        /// </summary>
        public static string endDateTitle {
            get {
                return ResourceManager.GetString("endDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting ends.
        /// </summary>
        public static string endOfVoting {
            get {
                return ResourceManager.GetString("endOfVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string favorite {
            get {
                return ResourceManager.GetString("favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import new songs.
        /// </summary>
        public static string import {
            get {
                return ResourceManager.GetString("import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import new songs reads all the songs for your fan page wall into Kululu application..
        /// </summary>
        public static string importExplanation {
            get {
                return ResourceManager.GetString("importExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include end dates.
        /// </summary>
        public static string includeEndDate {
            get {
                return ResourceManager.GetString("includeEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managers.
        /// </summary>
        public static string managers {
            get {
                return ResourceManager.GetString("managers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual import.
        /// </summary>
        public static string manualImport {
            get {
                return ResourceManager.GetString("manualImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import admin posts.
        /// </summary>
        public static string manualImportTitle {
            get {
                return ResourceManager.GetString("manualImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodic posts to wall.
        /// </summary>
        public static string manualPostToWall {
            get {
                return ResourceManager.GetString("manualPostToWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kululu can post periodic messages to your fan page wall. The post will show the leading songs in your default playlist..
        /// </summary>
        public static string manualPostToWallExplanation {
            get {
                return ResourceManager.GetString("manualPostToWallExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of songs a user can add per playlist.
        /// </summary>
        public static string maxSongsTitle {
            get {
                return ResourceManager.GetString("maxSongsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New playlist.
        /// </summary>
        public static string newPlaylist {
            get {
                return ResourceManager.GetString("newPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        public static string playlist {
            get {
                return ResourceManager.GetString("playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of playlist.
        /// </summary>
        public static string playlistName {
            get {
                return ResourceManager.GetString("playlistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string playlists {
            get {
                return ResourceManager.GetString("playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist settings.
        /// </summary>
        public static string playlistSettings {
            get {
                return ResourceManager.GetString("playlistSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of wall post: video/image.
        /// </summary>
        public static string postImageOrVideo {
            get {
                return ResourceManager.GetString("postImageOrVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When posting a message to your fan page&apos;s wall, will it be a video or an image? We recommand choosing a picture, otherise content might be filtered by your page&apos;s spam filter..
        /// </summary>
        public static string postImageOrVideoExplanation {
            get {
                return ResourceManager.GetString("postImageOrVideoExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post to wall.
        /// </summary>
        public static string postToWall {
            get {
                return ResourceManager.GetString("postToWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votes.
        /// </summary>
        public static string ratings {
            get {
                return ResourceManager.GetString("ratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove manager.
        /// </summary>
        public static string removeManager {
            get {
                return ResourceManager.GetString("removeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as default.
        /// </summary>
        public static string setDefaultPlaylist {
            get {
                return ResourceManager.GetString("setDefaultPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string settingLanguageSelectorLabel {
            get {
                return ResourceManager.GetString("settingLanguageSelectorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default language:.
        /// </summary>
        public static string settingsLanguage {
            get {
                return ResourceManager.GetString("settingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default language for users of the application.
        /// </summary>
        public static string settingsLanguageExplanation {
            get {
                return ResourceManager.GetString("settingsLanguageExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;User selected&gt;.
        /// </summary>
        public static string settingsLanguageUserSelected {
            get {
                return ResourceManager.GetString("settingsLanguageUserSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs.
        /// </summary>
        public static string songLimit {
            get {
                return ResourceManager.GetString("songLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song limit.
        /// </summary>
        public static string songLimitTitle {
            get {
                return ResourceManager.GetString("songLimitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs.
        /// </summary>
        public static string songs {
            get {
                return ResourceManager.GetString("songs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchornize now.
        /// </summary>
        public static string synchornizeNow {
            get {
                return ResourceManager.GetString("synchornizeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize with facebook.
        /// </summary>
        public static string synchronize {
            get {
                return ResourceManager.GetString("synchronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization process updates the likes and comments for each song that appear in your page&apos;s playlists. Synchronization runs automatically every few minutes..
        /// </summary>
        public static string synchronizeExplanation {
            get {
                return ResourceManager.GetString("synchronizeExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can manually synchronize your playlists any time: .
        /// </summary>
        public static string synchronizeManually {
            get {
                return ResourceManager.GetString("synchronizeManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodic status updates.
        /// </summary>
        public static string timedUpdatePosts {
            get {
                return ResourceManager.GetString("timedUpdatePosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update wall when admin adds a new song.
        /// </summary>
        public static string updateWallAdmin {
            get {
                return ResourceManager.GetString("updateWallAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update wall when user adds a new song.
        /// </summary>
        public static string updateWallUser {
            get {
                return ResourceManager.GetString("updateWallUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ser.
        /// </summary>
        public static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string video {
            get {
                return ResourceManager.GetString("video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string viewProfile {
            get {
                return ResourceManager.GetString("viewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What?.
        /// </summary>
        public static string what {
            get {
                return ResourceManager.GetString("what", resourceCulture);
            }
        }
    }
}
