//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kululu.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kululu.Web.App_GlobalResources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;dir:ltr;&quot;&gt; The admin has just posted the following song to the page&apos;s wall: {0}.&lt;/div&gt;.
        /// </summary>
        public static string adminEmailSentBody {
            get {
                return ResourceManager.GetString("adminEmailSentBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact@kulu.lu.
        /// </summary>
        public static string adminEmailSentFromAddress {
            get {
                return ResourceManager.GetString("adminEmailSentFromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The kululu team.
        /// </summary>
        public static string adminEmailSentFromName {
            get {
                return ResourceManager.GetString("adminEmailSentFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update from Kululu.
        /// </summary>
        public static string adminEmailSentSubject {
            get {
                return ResourceManager.GetString("adminEmailSentSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string allow {
            get {
                return ResourceManager.GetString("allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved, Kululu ©.
        /// </summary>
        public static string allRightsReserved {
            get {
                return ResourceManager.GetString("allRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed succesfully.
        /// </summary>
        public static string completedSucessfully {
            get {
                return ResourceManager.GetString("completedSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string connect {
            get {
                return ResourceManager.GetString("connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured while answering your request. We are doing our best to solve it as you read these lines. Please try again soon..
        /// </summary>
        public static string defaultError {
            get {
                return ResourceManager.GetString("defaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t like.
        /// </summary>
        public static string disliked {
            get {
                return ResourceManager.GetString("disliked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback for playlist {0}.
        /// </summary>
        public static string FeedbackForPlaylist {
            get {
                return ResourceManager.GetString("FeedbackForPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback for unknown playlist.
        /// </summary>
        public static string FeedbackForUnknownPlaylist {
            get {
                return ResourceManager.GetString("FeedbackForUnknownPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Feedback Received.
        /// </summary>
        public static string feedbackTitle {
            get {
                return ResourceManager.GetString("feedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kululu 1.0.
        /// </summary>
        public static string footerVesion {
            get {
                return ResourceManager.GetString("footerVesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since ever.
        /// </summary>
        public static string FromAlways {
            get {
                return ResourceManager.GetString("FromAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since last week.
        /// </summary>
        public static string fromWeekAgo {
            get {
                return ResourceManager.GetString("fromWeekAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since yesterday.
        /// </summary>
        public static string fromYesterday {
            get {
                return ResourceManager.GetString("fromYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use the appliction &quot;Like&quot; the page..
        /// </summary>
        public static string joinUsMessage {
            get {
                return ResourceManager.GetString("joinUsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kululu- Join Us.
        /// </summary>
        public static string joinUsTitle {
            get {
                return ResourceManager.GetString("joinUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kululu!.
        /// </summary>
        public static string kululu {
            get {
                return ResourceManager.GetString("kululu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re loading them.
        /// </summary>
        public static string loadingTitle {
            get {
                return ResourceManager.GetString("loadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In oder to begin, you must connect with application.
        /// </summary>
        public static string loginToApp {
            get {
                return ResourceManager.GetString("loginToApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating continues, the first places are:.
        /// </summary>
        public static string periodicWallPost {
            get {
                return ResourceManager.GetString("periodicWallPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        public static string termsOfService {
            get {
                return ResourceManager.GetString("termsOfService", resourceCulture);
            }
        }
    }
}
